{
 "title": "Exasol system overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Query stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance) (odbc_exasol_connections_COUNT)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries count by user",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "avg without(instance) (odbc_exasol_user_query_count_COUNT[2m])",
     "legendFormat": "{{USER_NAME}}"
    }
   ]
  },
  {
   "title": "Rows selected by user",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum by (USER_NAME) (odbc_exasol_rows_count_selected_ROW_COUNT)",
     "legendFormat": "{{USER_NAME}}"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_CPU)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance) (odbc_odbc_exasol_system_cpu_LA1)",
     "legendFormat": "la1"
    }
   ]
  },
  {
   "title": "Processes/Threads",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg without(instance) (odbc_odbc_exasol_system_cpu_PROCESSES_ACTIVE)",
     "legendFormat": "Processes active"
    },
    {
     "expr": "avg without(instance) (odbc_odbc_exasol_system_cpu_PROCESSES_TOTAL)",
     "legendFormat": "Processes total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance) (odbc_odbc_exasol_system_cpu_LA5)",
     "legendFormat": "la1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance) (odbc_odbc_exasol_system_cpu_LA15)",
     "legendFormat": "la1"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_TEMP_DB_RAM)",
     "legendFormat": "temp"
    },
    {
     "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_PERSISTENT_DB_RAM)",
     "legendFormat": "persistent"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_SWAP)",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read/write Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_HDD_READ)",
       "legendFormat": "read"
      },
      {
       "expr": "avg without (instance) (-1 * odbc_odbc_exasol_system_stat_HDD_WRITE)",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Read/write local",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_LOCAL_READ_SIZE)",
       "legendFormat": "read"
      },
      {
       "expr": "avg without (instance) (-1 * odbc_odbc_exasol_system_stat_LOCAL_WRITE_SIZE)",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Read/write remote",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_REMOTE_READ_SIZE)",
       "legendFormat": "read"
      },
      {
       "expr": "avg without (instance) (-1 * odbc_odbc_exasol_system_stat_REMOTE_WRITE_SIZE)",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Read/write cache",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_CACHE_READ_SIZE)",
       "legendFormat": "read"
      },
      {
       "expr": "avg without (instance) (-1 * odbc_odbc_exasol_system_stat_CACHE_WRITE_SIZE)",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Read/write local (duration)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_LOCAL_READ_DURATION)",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "Read/write remote (duration)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_REMOTE_READ_DURATION)",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "Read/write cache (duration)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_CACHE_READ_DURATION)",
       "legendFormat": "read"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "avg without (instance) (odbc_odbc_exasol_system_stat_NET)",
       "legendFormat": "net"
      }
     ]
    }
   ]
  }
 ]
}